version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: hscp_rota_db
    environment:
      POSTGRES_DB: hscp_rota
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
